version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: suqafuran_redis
    restart: always
    ports:
      - "6390:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: suqafuran_backend
    restart: always
    network_mode: "host"
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6390
      - REDIS_URL=redis://127.0.0.1:6390/0
    env_file:
      - ./backend/.env
    # depends_on:
    #   - redis
    # ports:
    #   - "8888:8888"
    command: >
      sh -c "sleep 5 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload"
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads

volumes:
  backend_uploads:
